name: polina_gift
description: Project on Polina's birthday.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  audioplayers: ^4.1.0
  camera: ^0.10.5+3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.3.7
  gallery_saver: ^2.3.2
  image_picker: ^1.0.2
  intl: ^0.17.0
  path_provider: ^2.1.0
  permission_handler: ^11.0.0
  riverpod: ^2.3.7
  share_plus: ^7.1.0
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  generate: true

  assets:
    - assets/images/
    - assets/anton/
    - assets/sounds/
